version: '3.8'

services:
  # 1. The Web Application (FastAPI)
  webapp:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: uas_webapp
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app  # Reload code on change (good for dev)
    restart: always

  # 2. Prometheus (Metrics Collection)
  prometheus:
    image: prom/prometheus:latest
    container_name: uas_prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always

  # 3. Grafana (Visualization)
  grafana:
    image: grafana/grafana:latest
    container_name: uas_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Default password
    restart: always

  # 4. Node Exporter (System Metrics)
  node-exporter:
    image: prom/node-exporter:latest
    container_name: uas_node_exporter
    ports:
      - "9100:9100"
    restart: always

  # 5. cAdvisor (Container Metrics)
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: uas_cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    restart: always
