global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'uas_webapp'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['webapp:8000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
